# Generated by Django 3.2.7 on 2021-09-15 11:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('thumb_img', models.ImageField(upload_to='blogs/thumbnil_img')),
                ('title_img', models.ImageField(upload_to='blogs/title_img')),
                ('blog', models.TextField()),
                ('detail_img1', models.ImageField(blank=True, null=True, upload_to='blogs/detail_image')),
                ('detail_img2', models.ImageField(blank=True, null=True, upload_to='blogs/detail_image')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Celebrity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=10)),
                ('image', models.ImageField(null=True, upload_to='celebrity')),
                ('slug', models.SlugField()),
                ('job', models.CharField(max_length=10)),
                ('overview', models.TextField()),
                ('biography', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='movies')),
                ('category', models.CharField(choices=[('action', 'ACTION'), ('adventure', 'ADVENTURE'), ('comedy', 'COMEDY'), ('drama', 'DRAMA'), ('romantic', 'ROMANTIC'), ('horror', 'HORROR'), ('thriller', 'THRILLER'), ('survivour', 'SURVIVOUR'), ('scifi', 'SCI-FI')], max_length=10)),
                ('language', models.CharField(choices=[('english', 'ENGLISH'), ('bangla', 'BANGLA')], max_length=10)),
                ('status', models.CharField(choices=[('recently added', 'RECENTLY ADDED'), ('most watched', 'MOST WATCHED'), ('popular', 'POPULAR'), ('coming soon', 'COMING SOON'), ('top rated', 'TOP RATED')], max_length=20)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('year_of_production', models.DateField()),
                ('views', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='MovieLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('D', 'DOWNLOAD'), ('W', 'WATCH')], max_length=1)),
                ('link', models.URLField()),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_link', to='movie.movie')),
            ],
        ),
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_favorite', models.BooleanField(default=False)),
                ('movies', models.ManyToManyField(to='movie.Movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
