# Generated by Django 3.2.7 on 2021-09-16 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='motto',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
