# Generated by Django 3.2.7 on 2021-09-17 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_alter_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='motto',
        ),
    ]
